# ==========================================
# BAXI3133 Group Project: Chest X-Ray CNN Classification
# S1G1 Group: B | Supervisor: Prof Ts Dr Burhanuddin
# ==========================================

# -*- coding: utf-8 -*-
"""CNN_classification_colab_FINAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-jodkjhSHaeEo9wXkn2bQfStG6fONtDC
"""

import os
import glob
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models, applications
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_curve, auc, classification_report, confusion_matrix
from sklearn.utils import class_weight
import cv2
import random
import pandas as pd

# Install kagglehub if not already
try:
    import kagglehub
except ImportError:
    !pip install -q kagglehub
    import kagglehub

print("Downloading Chest X-Ray dataset...")
path = kagglehub.dataset_download("paultimothymooney/chest-xray-pneumonia")
print("Dataset downloaded to:", path)

# The dataset structure: path/chest_xray/train, chest_xray/val, chest_xray/test
base_dir = os.path.join(path, "chest_xray")
print(f"Base directory: {base_dir}")

import random
import numpy as np
import tensorflow as tf

# Set seeds for Python, NumPy, and TensorFlow
random.seed(42)
np.random.seed(42)
tf.random.set_seed(42)

# For GPU determinism (may reduce performance)
tf.config.experimental.enable_op_determinism()

"""# Data Splitting"""

train_paths = glob.glob(os.path.join(base_dir, 'train', '*', '*.*'))
val_paths = glob.glob(os.path.join(base_dir, 'val', '*', '*.*'))
all_train_val_paths = train_paths + val_paths
print(f"Found {len(all_train_val_paths)} total images for training/validation.")

# Labels: 0 for NORMAL, 1 for PNEUMONIA
labels = [1 if 'PNEUMONIA' in path else 0 for path in all_train_val_paths]

# Stratified 80/20 split
X_train, X_val, y_train, y_val = train_test_split(
    all_train_val_paths, labels,
    test_size=0.2,
    stratify=labels,
    random_state=42
)

# Test set
X_test = glob.glob(os.path.join(base_dir, 'test', '*', '*.*'))
y_test = [1 if 'PNEUMONIA' in path else 0 for path in X_test]

print(f"Training images: {len(X_train)}")
print(f"Validation images: {len(X_val)}")
print(f"Testing images: {len(X_test)}")

"""# Exploratory Data Analysis (EDA)"""

# Combine labels into a single DataFrame for easy plotting
eda_df = pd.DataFrame({
    'Dataset Split': ['Train']*len(y_train) + ['Validation']*len(y_val) + ['Test']*len(y_test),
    'Label': y_train + y_val + y_test
})

# Map numeric labels back to string names for readability
eda_df['Class'] = eda_df['Label'].map({0: 'Normal', 1: 'Pneumonia'})

# Plot the distribution
plt.figure(figsize=(10, 6))
sns.countplot(data=eda_df, x='Dataset Split', hue='Class', palette='viridis')
plt.title('Chest X-Ray Class Distribution Across Splits', fontsize=14, fontweight='bold')
plt.ylabel('Number of Images', fontsize=12)
plt.xlabel('Split', fontsize=12)
plt.legend(title='Diagnosis')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

print("--- Exact Image Counts ---")
for split in ['Train', 'Validation', 'Test']:
    counts = eda_df[eda_df['Dataset Split'] == split]['Class'].value_counts().to_dict()
    print(f"{split}: {counts}")

"""# Computing Class Weights"""

# Calculate balanced class weights
weights = class_weight.compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train
)

# Convert to a dictionary format that Keras requires
class_weights_dict = dict(enumerate(weights))
print(f"Class 0 (Normal) Weight: {class_weights_dict[0]:.4f}")
print(f"Class 1 (Pneumonia) Weight: {class_weights_dict[1]:.4f}")

"""# Pipeline & Augmentation"""

AUTOTUNE = tf.data.AUTOTUNE

def parse_image(file_path, label):
    # Read and decode the image
    img = tf.io.read_file(file_path)
    img = tf.image.decode_jpeg(img, channels=3)
    # Resize to standardized input
    img = tf.image.resize(img, [224, 224])
    # Keep as float32 in [0, 255] range and let EfficientNet handle its own preprocessing
    return img, label

def build_dataset(paths, labels, is_training=False):
    dataset = tf.data.Dataset.from_tensor_slices((paths, labels))
    dataset = dataset.map(parse_image, num_parallel_calls=AUTOTUNE)
    if is_training:
        dataset = dataset.shuffle(buffer_size=2000)
    dataset = dataset.batch(32).prefetch(AUTOTUNE)
    return dataset

# Initialize Datasets
train_ds = build_dataset(X_train, y_train, is_training=True)
val_ds = build_dataset(X_val, y_val)
test_ds = build_dataset(X_test, y_test)

"""# Model Architecture"""

# Image Augmentation Layer
data_augmentation = tf.keras.Sequential([
    layers.RandomRotation(factor=10/360.0),
    layers.RandomZoom(height_factor=(-0.1, 0.1), width_factor=(-0.1, 0.1)),
    layers.RandomTranslation(height_factor=0.1, width_factor=0.1),
    layers.RandomBrightness(factor=0.1)
], name="augmentation_layer")

# Use standard ImageNet weights
base_model = applications.EfficientNetB0(
    include_top=False,
    input_shape=(224, 224, 3),
    weights='imagenet'
)
# Freeze the base model
base_model.trainable = False

# Build the top classifier
model = models.Sequential([
    data_augmentation,
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dropout(0.3),
    layers.Dense(1, activation='sigmoid')
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss='binary_crossentropy',
    metrics=['accuracy', tf.keras.metrics.AUC(name='auc')]
)

model.summary()

"""# Training Loop"""

# Callbacks for early stopping and saving the best model
callbacks = [
    tf.keras.callbacks.EarlyStopping(monitor='val_auc', patience=5, mode='max', restore_best_weights=True)
]
# Train the model WITH class weights
history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=15,
    callbacks=callbacks,
    class_weight=class_weights_dict
)

"""# Plotting the Training History"""

fig, ax = plt.subplots(1, 2, figsize=(14, 5))

# Plot 1: Model Loss
ax[0].plot(history.history['loss'], label='Train Loss', color='blue', linewidth=2)
ax[0].plot(history.history['val_loss'], label='Validation Loss', color='orange', linewidth=2)
ax[0].set_title('Model Loss over Epochs', fontsize=14)
ax[0].set_xlabel('Epochs', fontsize=12)
ax[0].set_ylabel('Binary Crossentropy Loss', fontsize=12)
ax[0].legend()
ax[0].grid(True, linestyle='--', alpha=0.6)

# Plot 2: Model AUC
ax[1].plot(history.history['auc'], label='Train AUC', color='green', linewidth=2)
ax[1].plot(history.history['val_auc'], label='Validation AUC', color='red', linewidth=2)
ax[1].set_title('Model AUC over Epochs', fontsize=14)
ax[1].set_xlabel('Epochs', fontsize=12)
ax[1].set_ylabel('Area Under Curve (AUC)', fontsize=12)
ax[1].legend()
ax[1].grid(True, linestyle='--', alpha=0.6)

plt.tight_layout()
plt.show()

"""# Metrics Calculation"""

# Predict on Test Data
y_pred_probs = model.predict(test_ds).ravel()
y_true = np.concatenate([y for x, y in test_ds], axis=0)

# Youden's J threshold
fpr, tpr, thresholds = roc_curve(y_true, y_pred_probs)
optimal_idx = np.argmax(tpr - fpr)
optimal_threshold = thresholds[optimal_idx]
print(f"Mathematical Youden's J Threshold: {optimal_threshold:.4f}")

# Clinical threshold
clinical_threshold = 0.50
print(f"\n--- Evaluating with Clinical Threshold of {clinical_threshold} ---")
y_pred_clinical = (y_pred_probs >= clinical_threshold).astype(int)

# Classification Report
print(classification_report(y_true, y_pred_clinical, target_names=['Normal', 'Pneumonia']))

# Clinical Confusion Matrix
cm_clinical = confusion_matrix(y_true, y_pred_clinical)
plt.figure(figsize=(6, 5))
sns.heatmap(cm_clinical, annot=True, fmt='d', cmap='Reds',
            xticklabels=['Normal', 'Pneumonia'],
            yticklabels=['Normal', 'Pneumonia'])
plt.title(f'Confusion Matrix (Threshold = {clinical_threshold})')
plt.ylabel('True Diagnosis')
plt.xlabel('AI Predicted Diagnosis')
plt.show()

# AUC Plot
roc_auc = auc(fpr, tpr)
plt.figure()
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (AUC = {roc_auc:.3f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.scatter(fpr[optimal_idx], tpr[optimal_idx], marker='o', color='red', label='Optimal Threshold')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic')
plt.legend(loc="lower right")
plt.show()

"""# Grad-CAM Implementation"""

def find_last_conv_layer(model):
    # Find the last convolutional layer in the base model
    conv_layers = [layer for layer in model.layers if isinstance(layer, tf.keras.layers.Conv2D)]
    return conv_layers[-1].name

def make_gradcam_heatmap(img_tensor, model):
    # 1. Extract the base EfficientNet model
    base_model = model.layers[1]

    # 2. Extract the classifier layers (GlobalAveragePooling, Dropout, Dense)
    classifier_layers = model.layers[2:]

    with tf.GradientTape() as tape:
        # 3. Pass the image through the base model to get the feature maps
        # (training=False ensures BatchNorm and Dropout behave correctly)
        last_conv_layer_output = base_model(img_tensor, training=False)

        # Tell the gradient tape to track our feature maps
        tape.watch(last_conv_layer_output)

        # 4. Pass the feature maps through the rest of the classifier
        preds = last_conv_layer_output
        for layer in classifier_layers:
            preds = layer(preds, training=False)

        # Since you are doing binary classification with 1 output node (sigmoid),
        # the prediction score is just the 0th index.
        class_channel = preds[0, 0]

    # Calculate gradients of the class score with respect to the feature map
    grads = tape.gradient(class_channel, last_conv_layer_output)

    # Average gradients spatially
    pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))

    # Multiply feature maps by importance weights
    last_conv_layer_output = last_conv_layer_output[0]
    heatmap = last_conv_layer_output @ pooled_grads[..., tf.newaxis]
    heatmap = tf.squeeze(heatmap)

    # Apply ReLU: Keep only features that have a positive influence
    heatmap = tf.maximum(heatmap, 0)

    # Normalize between 0 and 1
    max_val = tf.math.reduce_max(heatmap)
    if max_val == 0:
        max_val = 1e-8
    heatmap = heatmap / max_val

    return heatmap.numpy()

def display_gradcam(img_path, heatmap, alpha=0.4):
    # 1. Read the original image in BGR format
    img = cv2.imread(img_path)
    img = cv2.resize(img, (224, 224))

    img = np.uint8(img)

    # 2. Resize heatmap to match the image dimensions
    heatmap_resized = cv2.resize(heatmap, (img.shape[1], img.shape[0]))

    # 3. Rescale heatmap to 0-255 range and convert to uint8
    heatmap_rescaled = np.uint8(255 * heatmap_resized)

    # 4. Apply Jet colormap (OpenCV returns BGR by default)
    jet = cv2.applyColorMap(heatmap_rescaled, cv2.COLORMAP_JET)

    # 5. Superimpose the heatmap on the original image
    superimposed_img = cv2.addWeighted(img, 1 - alpha, jet, alpha, 0)

    # 6. Plot the results (Convert BGR to RGB for Matplotlib)
    plt.figure(figsize=(10, 5))
    plt.subplot(1, 2, 1)
    plt.title('Original Image')
    plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
    plt.axis('off')

    plt.subplot(1, 2, 2)
    plt.title('Grad-CAM Heatmap')
    plt.imshow(cv2.cvtColor(superimposed_img, cv2.COLOR_BGR2RGB))
    plt.axis('off')

    plt.tight_layout()
    plt.show()

sample_pneumonia_path = [p for p in X_test if 'PNEUMONIA' in p][0]
img_tensor, _ = parse_image(sample_pneumonia_path, 1)
img_tensor = tf.expand_dims(img_tensor, axis=0)

heatmap = make_gradcam_heatmap(img_tensor, model)
display_gradcam(sample_pneumonia_path, heatmap)

"""# Single Image Inference"""

def predict_and_explain_xray(img_path, model, threshold=0.50):
    print(f"\nProcessing X-Ray: {os.path.basename(img_path)}")
    true_diagnosis = "Pneumonia" if "PNEUMONIA" in img_path.upper() else "Normal"

    # 1. Preprocess the image
    img_tensor, _ = parse_image(img_path, label=0) # Dummy label for the parser
    img_tensor_batch = tf.expand_dims(img_tensor, axis=0) # Add batch dimension for the model
    # 2. Make Prediction
    prob = model.predict(img_tensor_batch, verbose=0)[0][0]
    # 3. Apply Clinical Logic
    prediction = "Pneumonia" if prob >= threshold else "Normal"
    confidence = prob if prediction == "Pneumonia" else (1 - prob)
    is_correct = (prediction == true_diagnosis)
    status_icon = "✅ MATCH" if is_correct else "❌ MISMATCH"

    print("-" * 35)
    print(f"Ground Truth   : {true_diagnosis}")
    print(f"AI Diagnosis   : {prediction} ({status_icon})")
    print(f"Confidence     : {confidence:.2%}")
    print(f"Raw Prob       : {prob:.4f}")
    print("-" * 35)
    # 4. Generate and display Grad-CAM
    heatmap = make_gradcam_heatmap(img_tensor_batch, model)
    display_gradcam(img_path, heatmap)

# test on 3 random guess
print("=== Real-World Clinical Inference Test ===")
sample_images = random.sample(X_test, 3)
for image_path in sample_images:
    predict_and_explain_xray(image_path, model, threshold=clinical_threshold)
